### ISSUE TITLE
Readme example doesn't work

### ISSUE THREAD

**Issue by Rigwarl** [khalidhoffman/pug-bem-lexer#3]
Hi again, example code
```
const pugString = `.block.-a-modifier
  ._some-element`;

pug.render(pugString, {
  plugins : [
    { lex : require('pug-bem-lexer') }
  ]
});
```
return
```
<div class="block block--a-modifier">
  <div class="_some-element"></div>
</div>
```
without element
```
const pugString = '.block.-a-modifier';
```
return
```
<div class="block -a-modifier"></div>
```

**Comment by khalidhoffman** [comment]
Hi @Rigwarl. Your issue highlighted some of pug's functionality that pug-bem-lexer does not address. Thank you for that! I've given it a slight rewrite under a new repo, [pug-bemify](https://github.com/khalidhoffman/pug-bemify). pug-bemify resolves the issue that you've highlighted and maintains the same functionality as pug-bem-lexer. Give it a try. I should also note the plugin usage syntax has changed, so be sure to review the readme. Any feedback is welcome. Thanks again!
